### ISSUE TITLE
Constructors in eigen_typekit are not thread-safe

### ISSUE THREAD

**Issue by meyerj** [orocos/rtt_geometry#34]
Currently constructors in package `eigen_typekit` have a local instance of the respective type which is initialized and returned by reference from the implemented `operator()`. This is not thread-safe at all because constructors are singletons registered once when the typekit is loaded.

Each call to `operator()` should therefore return a new instance by value.

**Comment by ahoarau** [comment]
Addressed in https://github.com/orocos/rtt_geometry/pull/26/commits/b8e97bc5203075b39890645a83ce385394d5eacb

**Comment by meyerj** [comment]
Thanks for the patch!

Some functors still have mutable `ptr` member variables with a single instance that gets overwritten and is returned by value for each invocation (and in some cases the `ptr` instance is unused now). That is better than to return by const reference, but not thread-safe if the constructors are invoked concurrently from different threads. I suggest to eliminate all member variables and only return new instances, either a temporary or an instance created as a local variable and returned by value.

**Comment by ahoarau** [comment]
I added the patch. Sorry I got confused by who was holding the data. Should be good for merge now

**Comment by meyerj** [comment]
Fixed in https://github.com/orocos/rtt_geometry/pull/26. Thanks to @ahoarau!
